### ISSUE TITLE
Issue when using with IE11

### ISSUE THREAD

**Issue by singsa** [prokki/twbs-toggle-buttons#2]
When using with IE11, an error is throw at

**e.target.dispatchEvent(new Event("twbsToggleButtons:activate"));**

The proposed fix is to replace it with the following

**var event;
if(typeof(Event) === 'function') {
    event = new Event('twbsToggleButtons:activate');
}else{
    event = document.createEvent('Event');
    event.initEvent('twbsToggleButtons:activate', true, true);
}
e.target.dispatchEvent(event);**

Tried and tested. Works great with all the browsers.

**Comment by prokki** [comment]
Hi @singsa 

thank you very much for your report!

I have added a [CONTRIBUTING.md](CONTRIBUTING.md) file (and fixed some smaller descriptions in markdowwn files) with a short description how to contribute easy **and** i have added yourself as a collaborator. If you accept the invitation you can change upcoming issues by yourself.

Of course I have added your fix of issue #2 to version 0.0.4 (still in branch 0.0.4) and requested a PR #3 . Feel free to check the branch and mark necessary changes or accept the pull request.
